services:
  postgres:
    image: postgres:latest
    container_name: task_management_api_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task-management-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste1234567
